apiVersion: v1
kind: Template
message: |-
  The following service(s) have been created in your project: ${APPLICATION_NAME}.

  Mattermost Version: ${MATTERMOST_VERSION}
       Database User: from secret `mattermost`
            Password: from secret `mattermost`
       Database Name: ${POSTGRESQL_DATABASE}

  Please see https://github.com/victorklijmeij/mattermost-enterprise-openshift/blob/master/README.md for detailed infomation.

  Dont forget to export service ${APPLICATION_NAME} as a route!
metadata:
  name: mattermost
  annotations:
    description: |-
      Community template for running Mattermost Enterprise Edition on Openshift (Origin)
      
      Mattermost Enterprise features require a valid license.
      
      https://about.mattermost.com  
 
    openshift.io/display-name: Mattermost
    tags: mattermost
    template.openshift.io/documentation-url: https://github.com/goern/mattermost-openshift/blob/master/README.md
    template.openshift.io/long-description: This template provides a Mattermost service, it depends on a Secret and MySQL.
    template.openshift.io/provider-display-name: Mattermost Community
    template.openshift.io/support-url: https://github.com/goern/mattermost-openshift/issues

objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "mattermost-data"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: '${APPLICATION_NAME}'
  spec:
    tags:  
    - name: '${MATTERMOST_VERSION}'
      annotations:
        description: The Mattermost image from quay.io/goern/mattermost-openshift
        openshift.io/display-name: 'Mattermost ${MATTERMOST_VERSION}'
        tags: mattermost
        version: '${MATTERMOST_VERSION}'
      from:
        kind: DockerImage
        name: 'quay.io/goern/mattermost-openshift:${MATTERMOST_VERSION}'
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: '${APPLICATION_NAME}'
  spec:
    selector:
      name: '${APPLICATION_NAME}'
    replicas: 2
    securityContext: {}
    serviceAccount: mattermost
    serviceAccountName: mattermost
    template:
      metadata:
        labels:
          name: '${APPLICATION_NAME}'
      spec:
        containers:
        - image: '${APPLICATION_NAME}'
          imagePullPolicy: Always
          name: '${APPLICATION_NAME}'
          volumeMounts:
          - mountPath: /opt/mattermost/data
            name: mattermost-data
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: mattermost-database
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mattermost-database
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: db_database
                name: mattermost
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8065
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8065
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8065
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 128Mi
        volumes:
        - persistentVolumeClaim:
            claimName: mattermost-data
          name: mattermost-data
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - '${APPLICATION_NAME}'
        from:
          kind: ImageStreamTag
          name: '${APPLICATION_NAME}:latest'
    - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: '${APPLICATION_NAME}'
  spec:
    ports:
    - name: 8065-tcp
      port: 8065
      protocol: TCP
      targetPort: 8065
    selector:
      deploymentconfig: '${APPLICATION_NAME}'
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: mattermost
  data:
    db_database: '${POSTGRESQL_DATABASE}'
    db_host: postgresql.mattermost.svc
parameters:
- name: APPLICATION_NAME
  required: true
  value: mattermost
- name: MATTERMOST_VERSION
  required: true
  value: v4.6.0
- name: VOLUME_CAPACITY
  required: true
  value: 10G
- description: Name of the PostgreSQL database accessed.
  displayName: PostgreSQL Database Name
  name: POSTGRESQL_DATABASE
  required: true
  value: mattermost
